maintenance/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.create, name='create-window'),
    path('view/', views.view, name='view-window'),
    path('update/', views.update, name='update-window'),
    path('delete/', views.delete, name='delete-window'),
    path('submit_create', views.submit_create, name='submit-create-window'),
    path('submit_update', views.submit_update, name='submit-update-window'),
    path('get_all_windows', views.get_all_windows,
         name='submit-get-all-windows'),
    path('get_window_details', views.get_window_details,
         name='submit-get-window-details'),
]

sso/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='saml-index'),
    path('attrs/', views.attrs, name='saml-attrs'),
    path('metadata/', views.metadata, name='saml-metadata'),
]

maintenance/forms.py
from django import forms
from django.forms import formset_factory
from django.utils import timezone
import user_variables

SUPPRESSION_TYPES = [
    ("DETECT_PROBLEMS_AND_ALERT", "Detect problems and alert"),
    ("DETECT_PROBLEMS_DONT_ALERT", "Detect problems but don't alert"),
    ("DONT_DETECT_PROBLEMS", "Disable problem detection during maintenance")
]
PLANNED_TYPES = [
    (True, "PLANNED"),
    (False, "UNPLANNED")
]
RECURRENCE_TYPES = [
    ("ONCE", "Once only"),
    ("DAILY", "Daily"),
    ("WEEKLY", "Day of week"),
    ("MONTHLY", "Day of month"),
]

CLUSTER_LIST = [("", "Choose Cluster")]
for cluster in user_variables.FULL_SET:
  CLUSTER_LIST.append((cluster, cluster))

DAYS_OF_WEEK = [
    ("", "Choose Day"),
    ("SUNDAY", "Sunday"),
    ("MONDAY", "Monday"),
    ("TUESDAY", "Tuesday"),
    ("WEDNESDAY", "Wednesday"),
    ("THURSDAY", "Thursday"),
    ("FRIDAY", "Friday"),
    ("SATURDAY", "Saturday"),
]

DAYS_OF_MONTH = []
for i in range(31):
  DAYS_OF_MONTH.append((i+1, i+1))


AVAILABLE_FILTER_FIELDS = [
    ("", "Entity Filter (Optional)"),
    ("APPLICATION", "Application"),
    ("APPLICATION_METHOD", "Application Method"),
    ("APPLICATION_METHOD_GROUP", "Application Method Group"),
    ("AUTO_SCALING_GROUP", "Auto Scaling Group"),
    ("AUXILIARY_SYNTHETIC_TEST", "Auxiliary Synthetic Test"),
    ("AWS_APPLICATION_LOAD_BALANCER", "AWS Application Load Balancer"),
    ("AWS_AVAILABILITY_ZONE", "AWS Availability Zone"),
    ("AWS_CREDENTIALS", "AWS Credentials"),
    ("AWS_LAMBDA_FUNCTION", "AWS Lambda Function"),
    ("AWS_NETWORK_LOAD_BALANCER", "AWS Network Load Balancer"),
    ("AZURE_API_MANAGEMENT_SERVICE", "Azure Api Management Service"),
    ("AZURE_APPLICATION_GATEWAY", "Azure Application Gateway"),
    ("AZURE_COSMOS_DB", "Azure Cosmos DB"),
    ("AZURE_CREDENTIALS", "Azure Credentials"),
    ("AZURE_EVENT_HUB", "Azure Event Hub"),
    ("AZURE_EVENT_HUB_NAMESPACE", "Azure Event Hub Namespace"),
    ("AZURE_FUNCTION_APP", "Azure Function App"),
    ("AZURE_IOT_HUB", "Azure Iot Hub"),
    ("AZURE_LOAD_BALANCER", "Azure Load Balancer"),
    ("AZURE_MGMT_GROUP", "Azure Mgmt Group"),
    ("AZURE_REDIS_CACHE", "Azure Redis Cache"),
    ("AZURE_REGION", "Azure Region"),
    ("AZURE_SERVICE_BUS_NAMESPACE", "Azure Service Bus Namespace"),
    ("AZURE_SERVICE_BUS_QUEUE", "Azure Service Bus Queue"),
    ("AZURE_SERVICE_BUS_TOPIC", "Azure Service Bus Topic"),
    ("AZURE_SQL_DATABASE", "Azure Sql Database"),
    ("AZURE_SQL_ELASTIC_POOL", "Azure Sql Elastic Pool"),
    ("AZURE_SQL_SERVER", "Azure Sql Server"),
    ("AZURE_STORAGE_ACCOUNT", "Azure Storage Account"),
    ("AZURE_SUBSCRIPTION", "Azure Subscription"),
    ("AZURE_TENANT", "Azure Tenant"),
    ("AZURE_VM", "Azure VM"),
    ("AZURE_VM_SCALE_SET", "Azure VM Scale Set"),
    ("AZURE_WEB_APP", "Azure Web App"),
    ("CF_APPLICATION", "CF Application"),
    ("CF_FOUNDATION", "CF Foundation"),
    ("CINDER_VOLUME", "Cinder Volume"),
    ("CUSTOM_APPLICATION", "Custom Application"),
    ("CUSTOM_DEVICE", "Custom Device"),
    ("CUSTOM_DEVICE_GROUP", "Custom Device Group"),
    ("DCRUM_APPLICATION", "Dcrum Application"),
    ("DCRUM_SERVICE", "Dcrum Service"),
    ("DCRUM_SERVICE_INSTANCE", "Dcrum Service Instance"),
    ("DEVICE_APPLICATION_METHOD", "Device Application Method"),
    ("DISK", "Disk"),
    ("DOCKER_CONTAINER_GROUP_INSTANCE", "Docker Container Group Instance"),
    ("DYNAMO_DB_TABLE", "Dynamo DB Table"),
    ("EBS_VOLUME", "Ebs Volume"),
    ("EC2_INSTANCE", "Ec2 Instance"),
    ("ELASTIC_LOAD_BALANCER", "Elastic Load Balancer"),
    ("ENVIRONMENT", "Environment"),
    ("EXTERNAL_SYNTHETIC_TEST_STEP", "External Synthetic Test Step"),
    ("GCP_ZONE", "GCP Zone"),
    ("GEOLOCATION", "Geolocation"),
    ("GEOLOC_SITE", "Geoloc Site"),
    ("GOOGLE_COMPUTE_ENGINE", "Google Compute Engine"),
    ("HOST", "Host"),
    ("HOST_GROUP", "Host Group"),
    ("HTTP_CHECK", "Http Check"),
    ("HTTP_CHECK_STEP", "Http Check Step"),
    ("HYPERVISOR", "Hypervisor"),
    ("KUBERNETES_CLUSTER", "Kubernetes Cluster"),
    ("KUBERNETES_NODE", "Kubernetes Node"),
    ("MOBILE_APPLICATION", "Mobile Application"),
    ("NETWORK_INTERFACE", "Network Interface"),
    ("NEUTRON_SUBNET", "Neutron Subnet"),
    ("OPENSTACK_PROJECT", "Openstack Project"),
    ("OPENSTACK_REGION", "Openstack Region"),
    ("OPENSTACK_VM", "Openstack VM"),
    ("OS", "OS"),
    ("PROCESS_GROUP", "Process Group"),
    ("PROCESS_GROUP_INSTANCE", "Process Group Instance"),
    ("RELATIONAL_DATABASE_SERVICE", "Relational Database Service"),
    ("SERVICE", "Service"),
    ("SERVICE_INSTANCE", "Service Instance"),
    ("SERVICE_METHOD", "Service Method"),
    ("SERVICE_METHOD_GROUP", "Service Method Group"),
    ("SWIFT_CONTAINER", "Swift Container"),
    ("SYNTHETIC_LOCATION", "Synthetic Location"),
    ("SYNTHETIC_TEST", "Synthetic Test"),
    ("SYNTHETIC_TEST_STEP", "Synthetic Test Step"),
    ("VIRTUALMACHINE", "Virtualmachine"),
    ("VMWARE_DATACENTER", "VMware Datacenter"),
]

TAGS_OR_ENTITIES_CHOICE = [
    ("", "Filter Type"),
    ("TAGS", "Tags"),
    ("ENTITIES", "Entities"),
]


class create_maintenance_window(forms.Form):
  cluster_name = forms.ChoiceField(
      label="Cluster Name",
      choices=CLUSTER_LIST,
      widget=forms.Select(
          attrs={
            'class': 'btn btn-secondary dropdown-toggle col-lg-4 col-sm-12 col-md-8'}
      )
  )
  tenant_name = forms.CharField(
      label="Tenant Name",
      max_length=100,
      widget=forms.Select(
          attrs={
              'class': 'btn btn-secondary dropdown-toggle col-lg-4 col-sm-12 col-md-8'}
      )
  )
  window_name = forms.CharField(
      label="Maintenance Window Name",
      max_length=100,
      widget=forms.TextInput(
          attrs={'class': 'form-control col-lg-4 col-sm-12 col-md-8'})
  )
  window_planned = forms.ChoiceField(
      choices=PLANNED_TYPES,
      widget=forms.Select(
          attrs={
              'class': 'btn btn-secondary dropdown-toggle col-lg-4 col-sm-12 col-md-8'}
      )
  )
  window_description = forms.CharField(
      label='Description',
      max_length=200,
      widget=forms.TextInput(
          attrs={'class': 'form-control col-lg-4 col-sm-12 col-md-8'})
  )
  window_recurrence = forms.ChoiceField(
      choices=RECURRENCE_TYPES,
      widget=forms.Select(
          attrs={
              'class': 'btn btn-secondary dropdown-toggle col-lg-4 col-sm-12 col-md-8'}
      )
  )
  window_day_of_week = forms.ChoiceField(
      choices=DAYS_OF_WEEK,
      required=False,
      widget=forms.Select(
          attrs={
              'class': 'btn btn-secondary dropdown-toggle col-lg-4 col-sm-12 col-md-8'}
      )
  )
  window_day_of_month = forms.ChoiceField(
      choices=DAYS_OF_MONTH,
      required=False,
      widget=forms.Select(
          attrs={
              'class': 'form-control btn btn-secondary dropdown-toggle col-lg-4 col-sm-12 col-md-8'}
      )
  )
  window_supression = forms.ChoiceField(
      choices=SUPPRESSION_TYPES,
      widget=forms.Select(
          attrs={
              'class': 'btn btn-secondary dropdown-toggle col-lg-4 col-sm-12 col-md-8'}
      )
  )
  window_start_time = forms.TimeField(
      label='Window Start Time',
      input_formats=["%H:%M"],
      required=False,
      widget=forms.TimeInput(
          attrs={'class': 'form-control col-lg-4 col-sm-12 col-md-8'})
  )
  window_duration = forms.IntegerField(
      label='Window Duration (in Minutes)',
      required=False,
      widget=forms.TextInput(
          attrs={'class': 'form-control col-lg-4 col-sm-12 col-md-8'})
  )
  window_maintenance_start = forms.DateField(
      label="Maintenance Start (Format Example: 2019-01-15 23:00)",
      input_formats=['%Y-%m-%d %H:%M'],
      widget=forms.DateInput(
          attrs={'class': 'form-control col-lg-4 col-sm-12 col-md-8'})
  )
  window_maintenance_end = forms.DateField(
      label="Maintenance End (Format Example: 2019-01-15 23:00)",
      input_formats=['%Y-%m-%d %H:%M'],
      widget=forms.TextInput(
          attrs={'class': 'form-control col-lg-4 col-sm-12 col-md-8'})
  )

  def fields_required(self, fields):
    #    """Used for conditionally marking fields as required."""
    for field in fields:
      if not self.cleaned_data.get(field, ''):
        msg = forms.ValidationError("This field is required.")
        self.add_error(field, msg)

  def clean(self):
    recurrence = self.cleaned_data.get('window_recurrence')
    filtering = self.cleaned_data.get('window_add_filters')

    if recurrence != "ONCE":
      self.fields_required(['window_start_time'])
      self.fields_required(['window_duration'])
    else:
      self.cleaned_data['window_start_time'] = None
      self.cleaned_data['window_duration'] = None

    if recurrence == "WEEKLY":
      self.fields_required(['window_day_of_week'])
    else:
      self.cleaned_data['window_day_of_week'] = None

    if recurrence == "MONTHLY":
      self.fields_required(['window_day_of_month'])
    else:
      self.cleaned_data['window_day_of_month'] = None

    if filtering:
      self.fields_required(['tags_list'])
    else:
      self.cleaned_data['tags_list'] = None

    return self.cleaned_data


class update_maintenance_window(forms.Form):
  cluster_name = forms.ChoiceField(
      label="Cluster Name",
      choices=CLUSTER_LIST,
      widget=forms.Select(
          attrs={
            'class': 'btn btn-secondary dropdown-toggle col-lg-4 col-sm-12 col-md-8'}
      )
  )
  tenant_name = forms.CharField(
      label="Tenant Name",
      max_length=100,
      widget=forms.Select(
          attrs={
              'class': 'btn btn-secondary dropdown-toggle col-lg-4 col-sm-12 col-md-8'}
      )
  )
  window_id = forms.CharField(
      label="Maintenance Window ID",
      max_length=100,
      widget=forms.TextInput(
          attrs={'class': 'form-control col-lg-4 col-sm-12 col-md-8'})
  )
  window_name = forms.CharField(
      label="Maintenance Window Name",

maintenance/views.py
from django.http import HttpResponse
from django.http import HttpResponseBadRequest
from django.http import JsonResponse
from django.shortcuts import render
from sso.validate import is_member_of_group

from .forms import create_maintenance_window
from .forms import view_maintenance_window
from .forms import update_maintenance_window
from .forms import filter_set
from .process_window import create_filters_from_formset
from .process_window import parse_submit_form

from dynatrace.tenant import maintenance
import user_variables as uv

# Create your views here.


def create(request):
  # is_member_of_group(request, 'Maintenance Writer')
  form = create_maintenance_window()
  formset = filter_set
  return render(
      request,
      'maintenance/create.html',
      {
          'form': form,
          'formset': formset
      }
  )


def view(request):
  # is_member_of_group(request, 'Maintenance Viewer')
  if request.method == "POST":
    form = view_maintenance_window(request.POST)
    cluster = uv.FULL_SET[request.POST['cluster_name']]
    list_of_windows = maintenance.get_windows(
        cluster, request.POST['tenant_name'])
  else:
    form = view_maintenance_window()
    # Hard Coded for now, Philly will add logic
    list_of_windows = {'values': {}}
  return render(
      request,
      'maintenance/view.html',
      {
          'form': form,
          'list_of_windows': list_of_windows["values"]
      }
  )

# Create your views here.


def update(request):
  """Update Page for Maintenance Window"""
  # is_member_of_group(request, 'Maintenance Writer')
  form = update_maintenance_window()
  formset = filter_set
  return render(
      request,
      'maintenance/update.html',
      {
          'form': form,
          'formset': formset
      }
  )


def delete(request):
  """Delete AJAX for Maintenance Window"""
  # is_member_of_group(request, 'Maintenance Writer')
  if request.method == "POST":
    cluster = request.POST['cluster_name']
    tenant = request.POST['tenant_name']
    window_id = request.POST['window_id']

    window_details = maintenance.delete_window(
        uv.FULL_SET[cluster], tenant, window_id)
    if window_details == 204:
      return HttpResponse("Success")
  return HttpResponseBadRequest("Invalid!")


def submit_create(request):
  """Submit Maintenance Window info to Cluster/Tenant Combo"""
  # is_member_of_group(request, 'Maintenance Writer')
  if request.method == "POST":
    form = create_maintenance_window(request.POST)
    if form.is_valid():
      # Popping all the args to get strip the information to a valid formset

      cluster_name = request.POST['cluster_name']
      tenant_name = request.POST['tenant_name']
      payload = parse_submit_form(request.POST.copy())

      try:
        new_window = maintenance.create_window(
            uv.FULL_SET[cluster_name],
            tenant_name,
            payload
        )
        return JsonResponse(new_window, safe=False)
      except Exception as e:
        print(e)
        # return HttpResponseBadRequest(e)
    else:
      print("Invalid Form!")
      return HttpResponseBadRequest("Invalid Form!")
  return HttpResponseBadRequest("Invalid Protocol")


def submit_update(request):
  """Submit Maintenance Window info to Cluster/Tenant Combo"""
  # is_member_of_group(request, 'Maintenance Writer')
  if request.method == "POST":
    form = update_maintenance_window(request.POST)
    # print(request.POST)
    if form.is_valid():
      # Popping all the args to get strip the information to a valid formset
      post_data = request.POST.copy()
      window_id = post_data.pop('window_id')[0]
      cluster_name = request.POST['cluster_name']
      tenant_name = request.POST['tenant_name']
      payload = parse_submit_form(post_data)
      try:
        #print(payload)
        update_window = maintenance.update_window(
            uv.FULL_SET[cluster_name],
            tenant_name,
            window_id,
            payload
        )
        return JsonResponse(update_window, safe=False)
      except Exception as e:
        print(e)
        # return HttpResponseBadRequest(e)
    else:
      print("Invalid Form!")
      return HttpResponseBadRequest("Invalid Form!")
  return HttpResponseBadRequest("Invalid Protocol")


def get_window_details(request):
  """Extract Maintenance Window Information"""
  # is_member_of_group(request, 'Maintenance Writer')
  if request.method == "POST":
    cluster = request.POST['cluster_name']
    tenant = request.POST['tenant_name']
    window_id = request.POST['window_id']

    window_details = maintenance.get_window(
        uv.FULL_SET[cluster], tenant, window_id)
    return JsonResponse(window_details)
  return HttpResponseBadRequest("Invalid!")


def get_all_windows(request):
  # is_member_of_group(request, 'Maintenance Writer')
  if request.method == 'POST':
    # form = view_maintenance_window(request.POST)
    cluster = uv.FULL_SET[request.POST['cluster_name']]
    
    list_of_windows = maintenance.get_windows(
        cluster, request.POST['tenant_name'])
    return JsonResponse(list_of_windows)
  return HttpResponseBadRequest("Invalid!")

maintenance/templates/maintenance/create.html
{% extends "dashboard/base.html" %}
{% block title %}Create Window{% endblock title %}
{% block content %}
{% load static %}
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">Maintenance Windows</h1>
  <!-- Basic Card Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Create Window</h6>
    </div>
    <div class="card-body">
      <p>Maintenance windows are typically planned, recurring periods of system downtime during which your DevOps team
        can perform preventative maintenance and system upgrades outside of peak traffic hours. To avoid having
        Dynatrace report on any performance anomalies that may result from such events, set up maintenance windows below
        that correspond with your organization's maintenance window schedule.</p>
      <!-- Name your maintenance window text field--->
      <form id="create_form" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Create Maintenance Window</legend>
          {% for field in form%}
          <div id="div_id_{{ field.name }}">
            <div class="small mb-1" for="{{ field.name }}">{{ field.label }}</div>
            <div class="mb-1">
              {{ field }}
            </div>
          </div>
          {% endfor %}
          {{ formset.management_form }}
          <div id="form_set">
            {% for window_filters in formset.forms %}
            <div>
              {% for field in window_filters %}
              <span id="div_id_{{ field.name }}">
                {{ field }}
              </span>
              {% endfor %}
            </div>
            {% endfor %}
          </div>
          <div id="empty_form" style="display:none">
            <div>
              {{ formset.empty_form }}
            </div>
          </div>
        </fieldset>
        <div class="input-group-append" id="add_more_div">
          <button type="button" style="margin:5px;" class="btn btn-success add-form-row" id="add_more_button">+</button>
          <button type="button" style="margin:5px;" class="btn btn-danger del-form-row"
            id="remove_prev_button">-</button>
        </div>
        <button type="submit" id="submit_create" class="btn btn-success mb-4">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block page_level_additions %}
<!-- Page level plugins -->
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="{% static '\js\maintenance_window_create.js' %}"></script>
<script src="{% static '\js\maintenance_window_shared.js' %}"></script>
{% endblock page_level_additions %}

maintenance/templates/maintenance/update.html
{% extends "dashboard/base.html" %}
{% block title %}Update Window{% endblock title %}
{% block content %}
{% load static %}
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">Maintenance Windows</h1>
  <!-- Basic Card Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Update Windows</h6>
    </div>
    <div class="card-body">
      <p>Maintenance windows are typically planned, recurring periods of system downtime during which your DevOps team
        can perform preventative maintenance and system upgrades outside of peak traffic hours. To avoid having
        Dynatrace report on any performance anomalies that may result from such events, set up maintenance windows below
        that correspond with your organization's maintenance window schedule.</p>
      <!-- Name your maintenance window text field--->
      <form id="update_form" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Update Maintenance Window</legend>
          {% for field in form%}
          <div id="div_id_{{ field.name }}">
            <div class="small mb-1" for="{{ field.name }}">{{ field.label }}</div>
            <div class="mb-1">
              {{ field }}
            </div>
          </div>
          {% endfor %}
          {{ formset.management_form }}
          <div id="form_set">
            {% for window_filters in formset.forms %}
            <div>
              {% for field in window_filters %}
              <span id="div_id_{{ field.name }}">
                {{ field }}
              </span>
              {% endfor %}
            </div>
            {% endfor %}
          </div>
          <div id="empty_form" style="display:none">
            <div>
              {{ formset.empty_form }}
            </div>
          </div>
        </fieldset>
        <div class="input-group-append" id="add_more_div">
          <button type="button" style="margin:5px;" class="btn btn-success add-form-row" id="add_more_button">+</button>
          <button type="button" style="margin:5px;" class="btn btn-danger del-form-row"
            id="remove_prev_button">-</button>
        </div>
        <button type="submit" id="submit_update" class="btn btn-success mb-4">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block page_level_additions %}
<!-- Page level plugins -->
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="{% static '\js\maintenance_window_update.js' %}"></script>
<script src="{% static '\js\maintenance_window_shared.js' %}"></script>
{% endblock page_level_additions %}

maintenance/templates/maintenance/view.html
{% extends "dashboard/base.html" %}
{% block title %}View Window{% endblock title %}
{% block content %}
{% load static %}
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">Maintenance Windows</h1>
  <!-- Basic Card Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">View Windows</h6>
    </div>
    <div class="card-body">
      <p>Maintenance windows are typically planned, recurring periods of system downtime during which your DevOps team
        can perform preventative maintenance and system upgrades outside of peak traffic hours. To avoid having
        Dynatrace report on any performance anomalies that may result from such events, set up maintenance windows below
        that correspond with your organization's maintenance window schedule.</p>
      <!-- Name your maintenance window text field--->
      <form id="get_window_list" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Configured maintenance windows</legend>
          {% for field in form%}
          <div id="div_id_{{ field.name }}">
            <div class="small mb-1" for="{{ field.name }}">{{ field.label }}</div>
            <div class="mb-1">
              {{ field }}
            </div>
          </div>
          {% endfor %}
        </fieldset>
        <button type="submit" id="get_all_windows" class="btn btn-success">View Tenant</button>
      </form>
      <br />
      <div class="table-responsive">
        <table class="table table-striped table-bordered dt-responsive nowrap" id="dataTable" width="100%"
          cellspacing="0">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>ID</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
      <div>
        <button id="get_window_details" class="btn btn-success">View Window</button>
      </div>
      <br />
      <div class="table-responsive">
        <table class="table table-striped table-bordered dt-responsive nowrap" id="details_table" width="100%"
          cellspacing="0">
          <thead>
            <th>Field</th>
            <th>Value</th>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
      <div>
        <form id="update_window_details" method="POST">
          {% csrf_token %}
          <button type=submit id="update_window_details" class="btn btn-warning">Update Window</button>
        </form>
        <form id="delete_window" method="POST">
          {% csrf_token %}
          <button type=submit id="delete_window" class="btn btn-danger confirmModal">Delete Window</button>
        </form>
      </div>
    </div>
  </div>
  {% endblock content %}

  {% block page_level_additions %}
  <!-- Page level plugins -->
  <!-- <script src ="https://code.jquery.com/jquery-3.3.1.js"></script> -->
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
  <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/maintenance_view.css' %}">
  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
  <script>
    $(document).ready(function () {
      //$( '#collapseTwo' ).addClass("show");
      $('#nav-maintenance').addClass("active");
      $('#nav-maintenance-view').addClass("active");

    })
  </script>
  <script>
    conditional_day_of_week = $("#div_id_window_day_of_week")
    conditional_day_of_month = $("#div_id_window_day_of_month")
    conditional_start_time = $("#div_id_window_start_time")
    conditional_duration = $("#div_id_window_duration")

    function hide_unused_fields() {
      ($('#id_window_recurrence').val() === "WEEKLY") ? conditional_day_of_week.show(): conditional_day_of_week.hide();
      ($('#id_window_recurrence').val() === "MONTHLY") ? conditional_day_of_month.show(): conditional_day_of_month
      .hide();
      if ($('#id_window_recurrence').val() !== "ONCE") {
        conditional_start_time.show();
        conditional_duration.show();
      } else {
        conditional_start_time.hide();
        conditional_duration.hide();
      }
    }
    hide_unused_fields();
    $('#id_window_recurrence').on('change', hide_unused_fields);
  </script>
  <script src="{% static '\js\maintenance_window_shared.js' %}"></script>
  <script src="{% static '\js\maintenance_window_view.js' %}"></script>
  <script src="{% static '\js\jquery.confirmModal.min.js' %}"></script>
  {% endblock page_level_additions %}